<link rel="stylesheet" href="{{asset('assets/front/css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('assets/front/css/animate.min.css')}}">
<link rel="stylesheet" href="{{asset('assets/front/css/magnific-popup.css')}}">
<link rel="stylesheet" href="{{asset('assets/front/css/fontawesome-all.min.css')}}">
<link rel="stylesheet" href="{{asset('assets/front/css/imageRevealHover.css')}}">
<link rel="stylesheet" href="{{asset('assets/front/css/swiper-bundle.css')}}">
<link rel="stylesheet" href="{{asset('assets/front/css/flaticon.css')}}">
<link rel="stylesheet" href="{{asset('assets/front/css/slick.css')}}">
<link rel="stylesheet" href="{{asset('assets/front/css/spacing.css')}}">
<link rel="stylesheet" href="{{asset('assets/front/css/main.css')}}">
